version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8338:8000"
    volumes:
      - ./chatapp:/chatapp
    links:
      - redis
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  redis:
    build: ./redis